### ISSUE TITLE
Instance Role changes

### ISSUE THREAD

**Issue by terkalma** [dejonghe/aws-batch-example#1]
Based on the awesome work you've done, I tried to put together a very similar stack, without the lambda function.
My jobs were stuck in a `Runnable` state. After going through this article: https://aws.amazon.com/premiumsupport/knowledge-center/batch-job-stuck-runnable-status/ I saw that the recommended policy for the instance role is `AmazonEC2ContainerServiceforEC2Role`. (See under "Verify the container instance IAM role")

After updating `AmazonECSTaskExecutionRolePolicy` to `AmazonEC2ContainerServiceforEC2Role` here:
https://github.com/dejonghe/aws-batch-example/blob/master/cloudformation/batch/batch-example.yml#L129 my jobs started going through just fine.

**Comment by dejonghe** [comment]
Looking into this. Will update shortly.

**Comment by dejonghe** [comment]
This has been updated.
