### ISSUE TITLE
The default AMI may not be valid for all users

### ISSUE THREAD

**Issue by bwood** [dejonghe/aws-batch-example#4]
The first time I ran the cfn template I got a parameter validation error for the AMI image.  I fixed this by replacing the default ami id with the output of:
```
aws ec2 describe-images --owners amazon --filters 'Name=name,Values=amzn2-ami-hvm-2.0.????????-x86_64-gp2' 'Name=state,Values=available' --output json | jq -r '.Images | sort_by(.CreationDate) | last(.[]).ImageId'
```
So perhaps that default value should be removed since it won't be valid for all users. 

Maybe this resource value could be set with the Systems Manager Parameter Store.  ([Example](https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/))

**Comment by dejonghe** [comment]
I fixed this issue by using the SSM parameter maintained by the ECS team to automatically fetch the recommended version of the ECS Optimized AMI. This will work in all regions.
